### ISSUE TITLE
looser throw specifier on gcc 4.7.2

### ISSUE THREAD

**Issue by zupalex** [jupp0r/prometheus-cpp#456]
Hello,

I tried to compile prometheus-cpp v0.12.1 with gcc 4.7.2 and got hit by a couple of issues:

```shell
In file included from /src/core/src/detail/builder.cc:6:0:
/src/core/include/prometheus/registry.h:66:3: error: looser throw specifier for 'virtual prometheus::Registry::~Registry()'
In file included from /src/core/include/prometheus/registry.h:9:0,
                 from /src/core/src/detail/builder.cc:6:
/src/core/include/prometheus/collectable.h:19:11: error:   overriding 'virtual prometheus::Collectable::~Collectable() noexcept (true)'
```

Which can be fixed by changing `core/include/prometheus/Registry.hh`

```cpp
# was  ~Registry();
~Registry() throw();
```

And  `core/src/registry.cc`

```cpp
# was Registry::~Registry() = default;
Registry::~Registry() throw() = default;
```

Then another error is
```shell
/src/core/src/histogram.cc: In member function 'void prometheus::Histogram::ObserveMultiple(const std::vector<double>&, double)':
/src/core/src/histogram.cc:33:11: error: 'length_error' is not a member of 'std'
```

Fixed by adding to `core/src/histogram.cc`
```cpp
#include <stdexcept>
```

The test fails but at least prometheus-cpp can be compiled with -DENABLE_TESTING=0 with these changes. I tried to compile with gcc 6.3.0 after modifying the files above and it seems to work, however I did not do extensive testing so would not be able to say if there are adverse consequences to these changes.

Thanks.

**Comment by gjasny** [comment]
Hello,

I cleaned up all the includes with include-what-you-use and the missing include should be fixed. I tried GCC 4.7.4 from Ubuntu xenial and with some minor tweaks I was able to compile prometheus-cpp (including tests) with GCC 4.7.

But a base requirement of prometheus-cpp is C++11. If you really need this ancient compiler I'd suggest that you maintain a branch/patch on your own.

Thanks,
Gregor

**Comment by zupalex** [comment]
Thanks. We are working with debian 9 machines but still have some old debian 7 systems and upgrading the compiler there is not an option sadly. Hopefully they will go away soon enough, bit until then we need to compile Prometheus with 4.7.2. I understand that it's not supported officially but since it seemed to work alright with these few changes I figured I should mention it :-)

Thanks again.
