### ISSUE TITLE
Can not build with c++11 only(gcc 4.8)

### ISSUE THREAD

**Issue by owent** [jupp0r/prometheus-cpp#618]
Can not build with c++11 only(gcc 4.8)
OS: Linux

**Comment by gjasny** [comment]
The master requires C++14 (see #615). Please rely on the 1.0 branches.

**Comment by owent** [comment]
I create a PR #619  to fix this problem, maybe it's helpful and I have already test it under ubuntu 18.04 and gcc 4.8.

**Comment by gjasny** [comment]
Why can't you use C++14?

**Comment by owent** [comment]
> Out of curiosity: why can't you use C++14?

GCC 4.8 does not implement all libraries of C++14.
