### ISSUE TITLE
[regression] cannot convert 'std::shared_ptr<prometheus::Registry>' to 'const std::weak_ptr<prometheus::Collectable>&'

### ISSUE THREAD

**Issue by alejandro-colomar** [jupp0r/prometheus-cpp#497]
I was using prometheus-cpp 0.11.0.

I bumped the dependency to 0.12.1, and it still works fine.  But after bumping to 0.12.3, I got this error:

```
.../src/xxx.cpp:26:35: error: cannot convert 'std::shared_ptr<prometheus::Registry>' to 'const std::weak_ptr<prometheus::Collectable>&'
   26 |     _exposer->RegisterCollectable(_registry);
      |                                   ^~~~~~~~~
      |                                   |
      |                                   std::shared_ptr<prometheus::Registry>
```

**Comment by jupp0r** [comment]
You need to include

`prometheus/registry.h` to let the compiler know that `Registry` is a `Collectable`. It's not necessarily a regression, we cleaned up our includes here https://github.com/jupp0r/prometheus-cpp/commit/f448b2c3de42a89521a2d44850e8a82aa0878d84#diff-48b545e8f349d03cd863abf4de35b6df8cbec473c53ffe18960737fa1d1c6c2f and this one isn't strictly required. I can see that it's unergonomical and non-obvious though. What do you think @gjasny ?

**Comment by gjasny** [comment]
Feel free to re-add it with a iwyu keep pragma.

**Comment by alejandro-colomar** [comment]
The code wasn't mine.  I was given some old code and the task of reorganizing the dependencies...  Now that I see the include and the code, I think the code I was given should probably have included that `<prometheus/registry.h>` (it makes sense if it's using `prometheus::Registry`).  So I agree that this is probably not necessarily a problem you should fix.

**Comment by alejandro-colomar** [comment]
Hmm, sorry, I see that the code is already including that one.  I'll try some things in the following days and come back here.

**Comment by ichliebemath** [comment]
Hey, I am also getting this error using version v1.1.0 and v0.12.1. I used cmake and <prometheus/registry.h> was included already... Anyone who can help with this? @alejandro-colomar Could you explain a little more about this issue? 

Thanks in advance!

**Comment by alejandro-colomar** [comment]
On 2023-06-13 18:07, ichliebemath wrote:
> Hey, I am also getting this error using version v1.1.0 and v0.12.1. I used cmake and <prometheus/registry.h> was included already... Anyone who can help with this? @alejandro-colomar Could you explain a little more about this issue? 
> 
> Thanks in advance!
> 

Hi!

Do you still have the issue?  I haven't worked in C++ projects since
2 years ago, and have forgot most of the details about this issue,
but maybe I can help you.

Cheers,
Alex

-- 
<http://www.alejandro-colomar.es/>
GPG key fingerprint: A9348594CE31283A826FBDD8D57633D441E25BB5

**Comment by ichliebemath** [comment]
Hi Alex,

thank you for your help, I have figured out the problem 😅 Just because I forgot to add the prometheus-cpp-pull to the cmakelists...Now it also works fine for me.

Have a nice day :)

Cheers,
Meijie
